// グリフ正当性ゴールデン（契約 §4-5・T3 指示 4）: 「立体テロップ」extrude の
// (a) 正面（ロ・プの穴が抜けている） (b) 回転中の側面厚みが見える瞬間 (c) 裏面鏡文字、
// の 3 フレームを SHA-256 付きで evidence/artifacts へ収蔵する。(b)(c) は
// determinism-seek.mjs と同一の carouselScene（同じシーン定義で決定論・シーク安全・ゴールデンの
// 3 点を裏取りする — 3d-text-flat の様式を踏襲）。
import { copyFile, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { captureWithPuppeteer, renderOverlaySheet } from "../../src/rasterize.mjs";
import {
  compositeOverBackground,
  editFor,
  loadPuppeteerModule,
  makeProjectRoot,
  overlayFor,
  resolveChromePath,
  sha256File,
} from "./support/fixtures.mjs";
import { carouselScene, frontScene } from "./support/scenes.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

async function captureFrame({ label, scene, duration, frameIndex, fps }) {
  const projectRoot = await makeProjectRoot(`golden-${label}`);
  const workDir = join(projectRoot, "work");
  await mkdir(workDir, { recursive: true });
  const edit = editFor({ width: 640, height: 360, fps });
  const overlay = overlayFor(label, scene, { start: 0, duration });
  const sheetPath = join(workDir, "sheet.html");
  await writeFile(
    sheetPath,
    renderOverlaySheet({ overlays: [overlay], edit, projectRoot, duration }),
    "utf8",
  );
  const puppeteerModule = await loadPuppeteerModule();
  const chromePath = await resolveChromePath();
  const framesDirectory = join(workDir, "frames");
  await captureWithPuppeteer({
    sheetPath,
    chromePath,
    framesDirectory,
    overlayMovPath: join(workDir, "overlay.mov"),
    width: edit.output.width,
    height: edit.output.height,
    fps: edit.output.fps,
    duration,
    ffmpegCommand: "ffmpeg",
    puppeteerModule,
  });
  const frameFiles = (await readdir(framesDirectory)).filter((f) => f.endsWith(".png")).sort();
  const framePath = join(framesDirectory, frameFiles[frameIndex]);
  const outPath = join(ARTIFACTS_DIR, `golden-${label}.png`);
  const viewablePath = join(ARTIFACTS_DIR, `golden-${label}-viewable.png`);
  await copyFile(framePath, outPath);
  compositeOverBackground(framePath, viewablePath);
  const sha256 = await sha256File(outPath);
  await rm(projectRoot, { recursive: true, force: true });
  return { label, frame: frameFiles[frameIndex], sha256, path: outPath, viewablePath };
}

// (a) 正面。t=0（anim:none）— 「ロ」の穴・「プ」の半濁点リングが抜けて見えることを確認する
const frontResult = await captureFrame({
  label: "front-ro-pu-glyphs",
  scene: frontScene(),
  duration: 0.5,
  fps: 4,
  frameIndex: 0,
});

// (b) 回転中の側面厚み。carousel speed=1.5 の t=0.6s（frame 6）≈ 0.9rad — 正面と側面が
// 同時に見える角度（determinism-seek.mjs と同一シーン定義）
const sideResult = await captureFrame({
  label: "side-thickness-mid-rotation",
  scene: carouselScene(),
  duration: 2.4,
  fps: 10,
  frameIndex: 6,
});

// (c) 裏面鏡文字。carousel speed=1.5 の t=2.3s（frame 23, 終端）≈ 3.45rad（197.7°）—
// 裏返って文字が鏡文字に見える角度
const backResult = await captureFrame({
  label: "back-mirror",
  scene: carouselScene(),
  duration: 2.4,
  fps: 10,
  frameIndex: 23,
});

const result = {
  generated_at_note: "generated by evidence/3d-text-extrude/golden.mjs",
  frames: [frontResult, sideResult, backResult],
};
await writeFile(join(ARTIFACTS_DIR, "golden-result.json"), JSON.stringify(result, null, 2), "utf8");
console.log(JSON.stringify(result, null, 2));
