// ネットワーク到達ゼロ（契約 §4-6・T3 指示 4）: extrude 経路は opentype.js が
// `fetch(textDescriptor.font)` で自前にフォントを取得する（troika の XHR ロードとは別の経路）。
// 書き出し時は rasterize.mjs の embedThreeModels が texts[].font を data URI へ埋め込むため
// （flat と共通のロジック・拡張なし）、この fetch は data: スキームに解決されて外部へは出ない
// はずだが、それを puppeteer の request インターセプトで実測する。
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { renderOverlaySheet } from "../../src/rasterize.mjs";
import {
  editFor,
  launchBrowser,
  makeProjectRoot,
  overlayFor,
} from "./support/fixtures.mjs";
import { frontScene } from "./support/scenes.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

const edit = editFor({ width: 480, height: 270, fps: 10 });
const DURATION = 1.0;
const FRAME_COUNT = Math.round(DURATION * edit.output.fps);

const projectRoot = await makeProjectRoot("network-zero");
const workDir = join(projectRoot, "work");
await mkdir(workDir, { recursive: true });
const overlay = overlayFor("title", frontScene(), { start: 0, duration: DURATION });
const sheetPath = join(workDir, "sheet.html");
await writeFile(
  sheetPath,
  renderOverlaySheet({ overlays: [overlay], edit, projectRoot, duration: DURATION }),
  "utf8",
);

const { browser } = await launchBrowser();
const requests = [];
const pageErrors = [];
try {
  const page = await browser.newPage();
  // setRequestInterception(true) は file:// の大きな主ドキュメント（本シートはフォント・
  // three バンドルを base64 で埋め込むため数 MB になる）で goto() が固まる実測不具合
  // （3d-text-flat/network-zero.mjs で確認済み）があるため使わない。'request' イベントは
  // interception を有効化しなくても素通しで observe できる
  page.on("request", (request) => {
    requests.push({ url: request.url(), resourceType: request.resourceType() });
  });
  page.on("pageerror", (e) => pageErrors.push(String(e)));
  await page.setViewport({ width: edit.output.width, height: edit.output.height, deviceScaleFactor: 1 });
  await page.goto(pathToFileURL(sheetPath).href, { waitUntil: "load", timeout: 60000 });
  await page.evaluate(() => window.__akariReady);
  for (let frame = 0; frame < FRAME_COUNT; frame += 1) {
    await page.evaluate((seconds) => window.__akariSeek(seconds), frame / edit.output.fps);
  }
  await page.screenshot({
    path: join(ARTIFACTS_DIR, "network-zero-frame.png"),
    omitBackground: true,
  });
} finally {
  await browser.close();
}

// file: / data: / blob: はローカル完結。それ以外の scheme（http/https 等）だけを
// 「外部リクエスト」として数える
const LOCAL_SCHEMES = ["file:", "data:", "blob:", "about:"];
const isLocal = (url) => LOCAL_SCHEMES.some((scheme) => url.startsWith(scheme));
const fileRequests = requests.filter((r) => r.url.startsWith("file:"));
const dataRequests = requests.filter((r) => r.url.startsWith("data:"));
const localRequests = requests.filter((r) => isLocal(r.url));
const externalRequests = requests.filter((r) => !isLocal(r.url));

const result = {
  generated_at_note: "generated by evidence/3d-text-extrude/network-zero.mjs",
  scene: "texts[] extrude, front static, 立体テロップ",
  frameCount: FRAME_COUNT,
  totalRequestsObserved: requests.length,
  fileRequests: fileRequests.length,
  // opentype.js の fetch(textDescriptor.font) が data: へ解決されている直接証拠
  fontFetchResolvedAsDataUri: dataRequests.length > 0,
  localRequests: localRequests.map((r) => ({ url: r.url.slice(0, 160), resourceType: r.resourceType })),
  externalRequests: externalRequests.map((r) => r.url),
  externalRequestCountIsZero: externalRequests.length === 0,
  unexpectedPageErrors: pageErrors,
  unexpectedPageErrorCountIsZero: pageErrors.length === 0,
};

await rm(projectRoot, { recursive: true, force: true });
await writeFile(join(ARTIFACTS_DIR, "network-zero-result.json"), JSON.stringify(result, null, 2), "utf8");
console.log(JSON.stringify({
  totalRequestsObserved: result.totalRequestsObserved,
  fileRequests: result.fileRequests,
  fontFetchResolvedAsDataUri: result.fontFetchResolvedAsDataUri,
  externalRequestCountIsZero: result.externalRequestCountIsZero,
  unexpectedPageErrorCountIsZero: result.unexpectedPageErrorCountIsZero,
}, null, 2));
