// 5 プリセット（none / carousel / char-chaos / flip-wave / tumble）それぞれが extrude でも動く証跡
// （契約 §4「4 プリセット + none がそれぞれ動く証跡（各 1 フレームで可）」を extrude に適用。
// T3 指示 2「anim プリセット（5 種）は flat と同一コードパスで動くこと」の直接の実測）。
// 3d-text-flat/presets-smoke.mjs と同じ流儀（起動→1枚→終了を毎回独立に行い、重負荷環境向けに
// 各プリセット 2 回までリトライする）。
import { copyFile, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { captureWithPuppeteer, renderOverlaySheet } from "../../src/rasterize.mjs";
import {
  compositeOverBackground,
  countNonTransparentPixels,
  editFor,
  FONT_RELATIVE_PATH,
  loadPuppeteerModule,
  makeProjectRoot,
  overlayFor,
  readRgba,
  resolveChromePath,
} from "./support/fixtures.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

const PRESETS = [
  { preset: "none" },
  { preset: "carousel", seed: 1 },
  { preset: "char-chaos", seed: 2 },
  { preset: "flip-wave", seed: 3 },
  { preset: "tumble", seed: 4 },
];

function sceneFor(preset, seed) {
  return {
    texts: [{
      id: "smoke",
      text: "プリセット確認",
      font: FONT_RELATIVE_PATH,
      mode: "extrude",
      size: 0.5,
      color: "#ffd166",
      material: { metalness: 0.7, roughness: 0.3 },
      extrude: { depth: 0.22, bevelSize: 0.02, bevelThickness: 0.03 },
      layout: { type: "line", spacing: 0.65 },
      anim: seed === undefined ? { preset } : { preset, seed, speed: 1, stagger: 0.1, amplitude: 1 },
    }],
    camera: { position: [0, 0, 5.5], fov: 45, lookAt: [0, 0, 0] },
  };
}

const edit = editFor({ width: 480, height: 270, fps: 10 });

async function captureOnePreset(preset, seed) {
  const projectRoot = await makeProjectRoot(`preset-${preset}`);
  const workDir = join(projectRoot, "work");
  await mkdir(workDir, { recursive: true });
  const duration = 1.0;
  const overlay = overlayFor("smoke", sceneFor(preset, seed), { start: 0, duration });
  const sheetPath = join(workDir, "sheet.html");
  await writeFile(
    sheetPath,
    renderOverlaySheet({ overlays: [overlay], edit, projectRoot, duration }),
    "utf8",
  );
  const puppeteerModule = await loadPuppeteerModule();
  const chromePath = await resolveChromePath();
  const framesDirectory = join(workDir, "frames");
  await captureWithPuppeteer({
    sheetPath,
    chromePath,
    framesDirectory,
    overlayMovPath: join(workDir, "overlay.mov"),
    width: edit.output.width,
    height: edit.output.height,
    fps: edit.output.fps,
    duration,
    ffmpegCommand: "ffmpeg",
    puppeteerModule,
  });
  const frameFiles = (await readdir(framesDirectory)).filter((f) => f.endsWith(".png")).sort();
  const framePath = join(framesDirectory, frameFiles[6]); // t=0.6s
  const outPath = join(ARTIFACTS_DIR, `preset-${preset}.png`);
  const viewablePath = join(ARTIFACTS_DIR, `preset-${preset}-viewable.png`);
  await copyFile(framePath, outPath);
  compositeOverBackground(framePath, viewablePath);
  const nonTransparentPixels = countNonTransparentPixels(readRgba(outPath));
  await rm(projectRoot, { recursive: true, force: true });
  return { preset, seed: seed ?? null, frame: frameFiles[6], nonTransparentPixels, outPath };
}

const results = [];
for (const { preset, seed } of PRESETS) {
  let lastError;
  let entry = null;
  for (let attempt = 1; attempt <= 2 && !entry; attempt += 1) {
    try {
      entry = await captureOnePreset(preset, seed);
    } catch (error) {
      lastError = error;
      console.error(`preset ${preset} attempt ${attempt} failed: ${error.message}`);
    }
  }
  if (!entry) throw lastError;
  console.error(`preset ${preset}: nonTransparentPixels=${entry.nonTransparentPixels}`);
  results.push(entry);
}

const allRendered = results.every((r) => r.nonTransparentPixels > 0);
const result = {
  generated_at_note: "generated by evidence/3d-text-extrude/presets-smoke.mjs",
  text: "プリセット確認",
  presets: results,
  allPresetsRendered: allRendered,
};
await writeFile(join(ARTIFACTS_DIR, "presets-smoke-result.json"), JSON.stringify(result, null, 2), "utf8");
console.log(JSON.stringify({
  allPresetsRendered: allRendered,
  presets: results.map((r) => ({ preset: r.preset, nonTransparentPixels: r.nonTransparentPixels })),
}, null, 2));
