// グリフ正当性ゴールデン（契約 §4-5）: 「アカリビデオ」筒シーンの裏面鏡文字が写った
// フレーム + 「ロ」「プ」を含むテキストのフレームを、SHA-256 付きで evidence/artifacts へ
// 収蔵する。determinism-seek.mjs のシーンと同一シーン定義を再利用する（同じシーンで
// 決定論・シーク安全・ゴールデンの 3 点を裏取りしている）。
import { copyFile, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { captureWithPuppeteer, renderOverlaySheet } from "../../src/rasterize.mjs";
import {
  compositeOverBackground,
  editFor,
  loadPuppeteerModule,
  makeProjectRoot,
  overlayFor,
  resolveChromePath,
  sha256File,
} from "./support/fixtures.mjs";
import { cylinderScene, roProScene } from "./support/scenes.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

async function captureFrame({ label, scene, duration, frameIndex, fps }) {
  const projectRoot = await makeProjectRoot(`golden-${label}`);
  const workDir = join(projectRoot, "work");
  await mkdir(workDir, { recursive: true });
  const edit = editFor({ width: 640, height: 360, fps });
  const overlay = overlayFor(label, scene, { start: 0, duration });
  const sheetPath = join(workDir, "sheet.html");
  await writeFile(
    sheetPath,
    renderOverlaySheet({ overlays: [overlay], edit, projectRoot, duration }),
    "utf8",
  );
  const puppeteerModule = await loadPuppeteerModule();
  const chromePath = await resolveChromePath();
  const framesDirectory = join(workDir, "frames");
  await captureWithPuppeteer({
    sheetPath,
    chromePath,
    framesDirectory,
    overlayMovPath: join(workDir, "overlay.mov"),
    width: edit.output.width,
    height: edit.output.height,
    fps: edit.output.fps,
    duration,
    ffmpegCommand: "ffmpeg",
    puppeteerModule,
  });
  const frameFiles = (await readdir(framesDirectory)).filter((f) => f.endsWith(".png")).sort();
  const framePath = join(framesDirectory, frameFiles[frameIndex]);
  const outPath = join(ARTIFACTS_DIR, `golden-${label}.png`);
  const viewablePath = join(ARTIFACTS_DIR, `golden-${label}-viewable.png`);
  await copyFile(framePath, outPath);
  compositeOverBackground(framePath, viewablePath);
  const sha256 = await sha256File(outPath);
  await rm(projectRoot, { recursive: true, force: true });
  return { label, frame: frameFiles[frameIndex], sha256, path: outPath, viewablePath };
}

const cylinderResult = await captureFrame({
  label: "cylinder-mirror-back",
  scene: cylinderScene(),
  duration: 2.4,
  fps: 10,
  frameIndex: 12, // t=1.2s（determinism-seek.mjs と同じシーン・同じ中間フレーム）
});

const roProResult = await captureFrame({
  label: "ro-pu-glyphs",
  scene: roProScene(),
  duration: 0.5,
  fps: 4,
  frameIndex: 0,
});

const result = {
  generated_at_note: "generated by evidence/3d-text-flat/golden.mjs",
  frames: [cylinderResult, roProResult],
};
await writeFile(join(ARTIFACTS_DIR, "golden-result.json"), JSON.stringify(result, null, 2), "utf8");
console.log(JSON.stringify(result, null, 2));
