// ネットワーク到達ゼロ（契約 §4-6・指示 3）: 絵文字（フォントに無いグリフ）を含む texts[] を
// 書き出しても、troika-three-text の unicode-font-resolver フォールバック
// （cdn.jsdelivr.net/gh/lojjic/unicode-font-resolver）へ 1 件も到達しないことを、
// puppeteer の request インターセプトで実測する。欠落グリフは豆腐（不描画）でよい —
// 黙って CDN に行くことだけが禁止（three-runtime.js の disableTroikaUnicodeFontFallback）。
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { renderOverlaySheet } from "../../src/rasterize.mjs";
import {
  editFor,
  FONT_RELATIVE_PATH,
  launchBrowser,
  makeProjectRoot,
  overlayFor,
} from "./support/fixtures.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

// ZenKakuGothicNew-Black.ttf は絵文字グリフを持たない。U+1F600 (😀) は確実に欠落コードポイント
// になり、troika の per-codepoint 走査で「フォント側で見つからない」= unicode-font-resolver
// フォールバックの呼び出し条件（m.length > 0）に必ず入る
const emojiScene = () => ({
  texts: [{
    id: "emoji",
    text: "らくがき😀メモ",
    font: FONT_RELATIVE_PATH,
    mode: "flat",
    size: 0.6,
    color: "#ffffff",
    layout: { type: "line", spacing: 0.7 },
    anim: { preset: "char-chaos", speed: 1, stagger: 0.1, amplitude: 1, seed: 3 },
  }],
  camera: { position: [0, 0, 5.5], fov: 45, lookAt: [0, 0, 0] },
});

const edit = editFor({ width: 480, height: 270, fps: 10 });
const DURATION = 1.0;
const FRAME_COUNT = Math.round(DURATION * edit.output.fps);

const projectRoot = await makeProjectRoot("network-zero");
const workDir = join(projectRoot, "work");
await mkdir(workDir, { recursive: true });
const overlay = overlayFor("emoji", emojiScene(), { start: 0, duration: DURATION });
const sheetPath = join(workDir, "sheet.html");
await writeFile(
  sheetPath,
  renderOverlaySheet({ overlays: [overlay], edit, projectRoot, duration: DURATION }),
  "utf8",
);

const { browser } = await launchBrowser();
const requests = [];
const pageErrors = [];
try {
  const page = await browser.newPage();
  // setRequestInterception(true) は file:// の大きな主ドキュメント（本シートは
  // フォント・three バンドルを base64 で埋め込むため数 MB になる）で goto() が固まる
  // 実測不具合（continue() 後も load イベントが来ない）があるため使わない。
  // 'request' イベントは interception を有効化しなくても素通しで observe できる
  // （何が要求されたかを数えるだけならこれで十分）
  page.on("request", (request) => {
    requests.push({ url: request.url(), resourceType: request.resourceType() });
  });
  // "akari-three: troika unicode font fallback is disabled" は worker 側の
  // 意図した reject（見せ消し）。それ以外のエラーだけ拾う
  page.on("pageerror", (e) => {
    const text = String(e);
    if (!text.includes("troika unicode font fallback is disabled")) pageErrors.push(text);
  });
  await page.setViewport({ width: edit.output.width, height: edit.output.height, deviceScaleFactor: 1 });
  // 埋め込みフォント（base64 数 MB）+ three バンドルの解析があるため既定 30000ms より余裕を持たせる
  await page.goto(pathToFileURL(sheetPath).href, { waitUntil: "load", timeout: 60000 });
  await page.evaluate(() => window.__akariReady);
  for (let frame = 0; frame < FRAME_COUNT; frame += 1) {
    await page.evaluate((seconds) => window.__akariSeek(seconds), frame / edit.output.fps);
  }
  await page.screenshot({
    path: join(ARTIFACTS_DIR, "network-zero-frame.png"),
    omitBackground: true,
  });
} finally {
  await browser.close();
}

// file: / data: / blob: はローカル完結（blob: は troika-worker-utils が SDF ワーカーを
// 生成する際の in-page Blob URL — ネットワークへは出ない）。それ以外の scheme（http/https 等）
// だけを「外部リクエスト」として数える
const LOCAL_SCHEMES = ["file:", "data:", "blob:", "about:"];
const isLocal = (url) => LOCAL_SCHEMES.some((scheme) => url.startsWith(scheme));
const fileRequests = requests.filter((r) => r.url.startsWith("file:"));
const localRequests = requests.filter((r) => isLocal(r.url));
const externalRequests = requests.filter((r) => !isLocal(r.url));
const cdnRequests = requests.filter((r) => r.url.includes("jsdelivr") || r.url.includes("unicode-font-resolver"));

const result = {
  generated_at_note: "generated by evidence/3d-text-flat/network-zero.mjs",
  scene: "texts[] flat, char-chaos, text contains U+1F600 (😀) not covered by ZenKakuGothicNew-Black",
  frameCount: FRAME_COUNT,
  totalRequestsObserved: requests.length,
  fileRequests: fileRequests.length,
  localRequests: localRequests.map((r) => ({ url: r.url.slice(0, 160), resourceType: r.resourceType })),
  externalRequests: externalRequests.map((r) => r.url),
  cdnFallbackRequests: cdnRequests.map((r) => r.url),
  externalRequestCountIsZero: externalRequests.length === 0,
  cdnFallbackRequestCountIsZero: cdnRequests.length === 0,
  unexpectedPageErrors: pageErrors,
  unexpectedPageErrorCountIsZero: pageErrors.length === 0,
};

await rm(projectRoot, { recursive: true, force: true });
await writeFile(join(ARTIFACTS_DIR, "network-zero-result.json"), JSON.stringify(result, null, 2), "utf8");
console.log(JSON.stringify({
  totalRequestsObserved: result.totalRequestsObserved,
  fileRequests: result.fileRequests,
  externalRequestCountIsZero: result.externalRequestCountIsZero,
  cdnFallbackRequestCountIsZero: result.cdnFallbackRequestCountIsZero,
  unexpectedPageErrorCountIsZero: result.unexpectedPageErrorCountIsZero,
}, null, 2));
