// 性能予算（契約 §4-7）: プレビュー相当ページで 20 文字 flat + carousel の fps を実測する
// （契約は 60fps 予算・未達なら数値を添えて報告と定めている — 落第ではなく実測報告が義務）。
// overlay-runtime.js の tick() を rAF ループで駆動し、実際に描かれたフレーム数を壁時計で数える。
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import {
  editFor,
  FONT_RELATIVE_PATH,
  launchBrowser,
  makeProjectRoot,
  overlayFor,
  previewPageHtml,
  stageRuntimeScripts,
  startStaticServer,
} from "./support/fixtures.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

// 契約 §4-7 のとおり「20 文字 flat + carousel」。文字数を稼ぐため助詞混じりの実文にする
const TEXT_20_CHARS = "アカリビデオで動画編集がもっと楽しくなる";
console.error("char count:", [...TEXT_20_CHARS].length);

const scene = {
  texts: [{
    id: "perf",
    text: TEXT_20_CHARS,
    font: FONT_RELATIVE_PATH,
    mode: "flat",
    size: 0.3,
    color: "#ffd166",
    layout: { type: "cylinder", radius: 2.6, position: [0, 0, 0], rotation: [0, 0, 0] },
    anim: { preset: "carousel", speed: 0.6, stagger: 0.05, amplitude: 1, seed: 11 },
  }],
  camera: { position: [0, 0.3, 6.5], fov: 45, lookAt: [0, 0, 0] },
};

const edit = editFor({ width: 1280, height: 720, fps: 30 });
const DURATION = 20; // overlay 側の可視区間。実測は rAF ループで別途 wall-clock 駆動する
const projectRoot = await makeProjectRoot("perf-fps");
await mkdir(join(projectRoot, "work"), { recursive: true });
await stageRuntimeScripts(projectRoot);
const overlay = overlayFor("perf", scene, { start: 0, duration: DURATION });
await writeFile(join(projectRoot, "preview.html"), previewPageHtml({ overlay, edit }), "utf8");

const server = await startStaticServer(projectRoot);
const { browser } = await launchBrowser();
let measurement;
try {
  const page = await browser.newPage();
  page.on("pageerror", (e) => console.error("PAGEERROR:", String(e)));
  await page.setViewport({ width: edit.output.width, height: edit.output.height, deviceScaleFactor: 1 });
  await page.goto(`${server.url}/preview.html`, { waitUntil: "networkidle0", timeout: 60000 });
  await page.evaluate(() => window.__akariPreviewReady);
  await page.evaluate(() => window.akari.runtime.tick(0, true));
  await page.evaluate(async () => {
    const container = document.querySelector("#overlay-stage > div");
    for (let i = 0; i < 3000; i += 1) {
      const status = window.akari.threeRuntime.inspect(container).status;
      if (status === "ready") return;
      if (status === "error") throw new Error("perf scene failed to load");
      await new Promise((resolve) => setTimeout(resolve, 10));
    }
    throw new Error("perf scene did not become ready in time");
  });

  // 実測: 実時間 3 秒の壁時計窓（setTimeout で締め切る。rAF の自己スケジューリングに
  // 依存すると、システムが混雑して rAF 間隔が数秒級に伸びたとき「3000ms 分の rAF 経過」を
  // 待つループ自体が数十秒〜数分に膨れる実測不具合があった）。窓の中で rAF ごとに
  // tick(wall-clock seconds, true) を呼び、実際に処理できたフレーム数を数える
  // （threeRuntime.render 呼び出し = 実描画コスト込みで測る）
  measurement = await page.evaluate(() => new Promise((resolve) => {
    const durationMs = 3000;
    let frames = 0;
    const start = performance.now();
    let done = false;
    function finish() {
      if (done) return;
      done = true;
      resolve({ frames, elapsedMs: performance.now() - start });
    }
    function step(now) {
      if (done) return;
      const elapsedSeconds = (now - start) / 1000;
      window.akari.runtime.tick(elapsedSeconds, true);
      frames += 1;
      requestAnimationFrame(step);
    }
    setTimeout(finish, durationMs);
    requestAnimationFrame(step);
  }));

  const info = await page.evaluate(() => {
    const container = document.querySelector("#overlay-stage > div");
    return window.akari.threeRuntime.inspect(container);
  });
  measurement.rendererInfo = info;

  // 基準値: このマシン・この瞬間の Node<->Chrome CDP 往復コスト（実描画を一切含まない）。
  // fps が低い原因が「render() 自体が重い」のか「このセッションの外側の負荷で往復自体が
  // 重い」のかを切り分けるための実測（実行時の /usr/bin/top 実測: この評価直前の
  // load average が 2 桁〜3 桁台になることがある共有マシン）
  const roundTripStarted = performance.now();
  const ROUND_TRIP_SAMPLES = 20;
  for (let i = 0; i < ROUND_TRIP_SAMPLES; i += 1) {
    // eslint-disable-next-line no-await-in-loop
    await page.evaluate((n) => n + 1, i);
  }
  measurement.roundTripMsPerCall = (performance.now() - roundTripStarted) / ROUND_TRIP_SAMPLES;
} finally {
  await browser.close();
  await server.close();
}

const fps = measurement.frames / (measurement.elapsedMs / 1000);
const result = {
  generated_at_note: "generated by evidence/3d-text-flat/perf-fps.mjs",
  scene: `texts[] flat + carousel, ${[...TEXT_20_CHARS].length} chars, cylinder layout`,
  output: edit.output,
  measuredFrames: measurement.frames,
  elapsedMs: Math.round(measurement.elapsedMs),
  fps: Number(fps.toFixed(2)),
  budgetFps: 60,
  meetsBudget: fps >= 60,
  rendererInfo: measurement.rendererInfo,
  cdpRoundTripMsPerCall: Number(measurement.roundTripMsPerCall.toFixed(2)),
  note: "M 系 Mac 実機・ヘッドレス Chrome（software WebGL, SwiftShader）での実測。GPU 実機の"
    + "プレビュー（実ブラウザ）とは描画バックエンドが異なるため、絶対値は下振れしうる。"
    + "seek/screenshot コストを含まない純粋な render() 呼び出しの fps を rAF ループで実測している。"
    + "cdpRoundTripMsPerCall は実描画を含まない Node<->Chrome CDP 往復単体のコスト（同一セッション・"
    + "直後に実測） — fps が低い原因が render() 自体の重さか、セッション外の負荷による往復遅延かの"
    + "切り分けに使う",
};

const { rm } = await import("node:fs/promises");
await rm(projectRoot, { recursive: true, force: true });
await writeFile(join(ARTIFACTS_DIR, "perf-fps-result.json"), JSON.stringify(result, null, 2), "utf8");
console.log(JSON.stringify(result, null, 2));
