// ネットワーク到達ゼロ（契約の指示 4・§4-6）: physics 宣言を含むシートを書き出しても、
// 外部リクエストが 0 件であることを実測する（poly-decomp / matter-js も vendor 埋め込み済みで
// 実行時 npm/CDN 到達は無い）。様式は 3d-text-flat/network-zero.mjs
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { renderOverlaySheet } from "../../src/rasterize.mjs";
import { editFor, launchBrowser, makeProjectRoot, overlayFor } from "./shared/fixtures.mjs";
import { personSilhouetteScene } from "./shared/scenes.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

const edit = editFor({ width: 480, height: 270, fps: 10 });
const DURATION = 1.0;
const FRAME_COUNT = Math.round(DURATION * edit.output.fps);

const projectRoot = await makeProjectRoot("network-zero");
try {
  const workDir = join(projectRoot, "work");
  await mkdir(workDir, { recursive: true });
  // polygon collider（poly-decomp 経由）を含むシーンで確認する — vendor 追加の主目的そのもの
  const scene = personSilhouetteScene({ duration: DURATION, seed: 22 });
  const overlay = overlayFor("phys", scene, { start: 0, duration: DURATION });
  const sheetPath = join(workDir, "sheet.html");
  await writeFile(
    sheetPath,
    renderOverlaySheet({ overlays: [overlay], edit, projectRoot, duration: DURATION }),
    "utf8",
  );

  const { browser } = await launchBrowser();
  const requests = [];
  const pageErrors = [];
  try {
    const page = await browser.newPage();
    page.on("request", (request) => {
      requests.push({ url: request.url(), resourceType: request.resourceType() });
    });
    page.on("pageerror", (e) => pageErrors.push(String(e)));
    await page.setViewport({ width: edit.output.width, height: edit.output.height, deviceScaleFactor: 1 });
    await page.goto(pathToFileURL(sheetPath).href, { waitUntil: "load", timeout: 60000 });
    await page.evaluate(() => window.__akariReady);
    for (let frame = 0; frame < FRAME_COUNT; frame += 1) {
      await page.evaluate((seconds) => window.__akariSeek(seconds), frame / edit.output.fps);
    }
    await page.screenshot({
      path: join(ARTIFACTS_DIR, "network-zero-frame.png"),
      omitBackground: true,
    });
  } finally {
    await browser.close();
  }

  const LOCAL_SCHEMES = ["file:", "data:", "blob:", "about:"];
  const isLocal = (url) => LOCAL_SCHEMES.some((scheme) => url.startsWith(scheme));
  const fileRequests = requests.filter((r) => r.url.startsWith("file:"));
  const localRequests = requests.filter((r) => isLocal(r.url));
  const externalRequests = requests.filter((r) => !isLocal(r.url));

  const result = {
    generated_at_note: "generated by evidence/3d-text-physics/network-zero.mjs",
    scene: "personSilhouetteScene (physics + polygon collider via poly-decomp)",
    frameCount: FRAME_COUNT,
    totalRequestsObserved: requests.length,
    fileRequests: fileRequests.length,
    localRequests: localRequests.map((r) => ({ url: r.url.slice(0, 160), resourceType: r.resourceType })),
    externalRequests: externalRequests.map((r) => r.url),
    externalRequestCountIsZero: externalRequests.length === 0,
    unexpectedPageErrors: pageErrors,
    unexpectedPageErrorCountIsZero: pageErrors.length === 0,
  };

  await writeFile(
    join(ARTIFACTS_DIR, "network-zero-result.json"),
    JSON.stringify(result, null, 2),
    "utf8",
  );
  console.log(JSON.stringify({
    totalRequestsObserved: result.totalRequestsObserved,
    fileRequests: result.fileRequests,
    externalRequestCountIsZero: result.externalRequestCountIsZero,
    unexpectedPageErrorCountIsZero: result.unexpectedPageErrorCountIsZero,
  }, null, 2));
  if (!result.externalRequestCountIsZero || !result.unexpectedPageErrorCountIsZero) process.exitCode = 1;
} finally {
  await rm(projectRoot, { recursive: true, force: true });
}
