// 性能実測（契約の指示 6）: presim（11 文字 × duration 8s × dt 1/120）の所要 ms と
// バッファサイズを report 用に実測する。runPhysicsPresim は createInstance() の
// 読み込みチェーン内で同期実行されるため、計測は three-runtime.js 自身が inspect() で返す
// physicsPresimMs（内部で performance.now() により計測）をそのまま読む
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { renderOverlaySheet } from "../../src/rasterize.mjs";
import { editFor, launchBrowser, makeProjectRoot, overlayFor } from "./shared/fixtures.mjs";
import { basicFallScene } from "./shared/scenes.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

const edit = editFor({ width: 480, height: 270, fps: 10 });
const DURATION = 8.0;
const DT = 1 / 120;
// 11 文字（契約の指示 6 の指定どおり）。「アカリビデオ物理落下中」= 11 文字
const TEXT = "アカリビデオ物理落下中";

const projectRoot = await makeProjectRoot("perf");
try {
  const workDir = join(projectRoot, "work");
  await mkdir(workDir, { recursive: true });
  const scene = basicFallScene({ text: TEXT, duration: DURATION, dt: DT });
  const overlay = overlayFor("phys", scene, { start: 0, duration: DURATION });
  const sheetPath = join(workDir, "sheet.html");
  await writeFile(
    sheetPath,
    renderOverlaySheet({ overlays: [overlay], edit, projectRoot, duration: DURATION }),
    "utf8",
  );

  const { browser } = await launchBrowser();
  const samples = [];
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: edit.output.width, height: edit.output.height, deviceScaleFactor: 1 });
    // mount のたびに dispose→render で presim をやり直させ、複数回実測する（初回のみの
    // 偶然を避ける。同一ページ内なので Chrome の初回 JIT ウォームアップの影響だけ残る）
    await page.goto(pathToFileURL(sheetPath).href, { waitUntil: "networkidle0", timeout: 60000 });
    await page.evaluate(() => window.__akariReady);
    for (let trial = 0; trial < 5; trial += 1) {
      const inspection = await page.evaluate(async () => {
        const container = document.querySelector(".akari-overlay-container > .scene-content");
        window.akari.threeRuntime.dispose(container);
        window.akari.threeRuntime.render(container, 0);
        for (let i = 0; i < 2000; i += 1) {
          const status = window.akari.threeRuntime.inspect(container).status;
          if (status === "ready" || status === "error") break;
          await new Promise((resolve) => setTimeout(resolve, 2));
        }
        return window.akari.threeRuntime.inspect(container);
      });
      samples.push(inspection.physics);
    }
  } finally {
    await browser.close();
  }

  const presimMsSamples = samples.map((s) => s.presimMs);
  const result = {
    generated_at_note: "generated by evidence/3d-text-physics/perf.mjs",
    scene: `basicFallScene (physics, ${[...TEXT].length} chars: "${TEXT}", duration=${DURATION}s, dt=1/120)`,
    charCount: samples[0].charCount,
    frameCount: samples[0].frameCount,
    dt: samples[0].dt,
    duration: samples[0].duration,
    bufferBytes: samples[0].bufferBytes,
    presimMsTrials: presimMsSamples,
    presimMsMedian: [...presimMsSamples].sort((a, b) => a - b)[Math.floor(presimMsSamples.length / 2)],
    presimMsMin: Math.min(...presimMsSamples),
    presimMsMax: Math.max(...presimMsSamples),
  };

  await writeFile(
    join(ARTIFACTS_DIR, "perf-result.json"),
    JSON.stringify(result, null, 2),
    "utf8",
  );
  console.log(JSON.stringify(result, null, 2));
} finally {
  await rm(projectRoot, { recursive: true, force: true });
}
