// restitution を振った 2 ケース（0.1 / 0.6）で挙動が変わることの smoke（契約の指示 4）。
// 同一 seed・同一初期配置で restitution だけを変え、跳ね返り後の最高到達高さ（バウンド後の
// 最大 y）を比較する。低反発ほど跳ねが小さく早く収束し、高反発ほど跳ね返りが大きく残ることを実測する
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { renderOverlaySheet } from "../../src/rasterize.mjs";
import { editFor, launchBrowser, makeProjectRoot, overlayFor } from "./shared/fixtures.mjs";
import { basicFallScene } from "./shared/scenes.mjs";

const ARTIFACTS_DIR = join(new URL(".", import.meta.url).pathname, "artifacts");
await mkdir(ARTIFACTS_DIR, { recursive: true });

const edit = editFor({ width: 480, height: 270, fps: 10 });
const DURATION = 4.0;
const FLOOR_Y = -2.6;

async function runCase(restitution) {
  const projectRoot = await makeProjectRoot(`restitution-${restitution}`);
  try {
    const workDir = join(projectRoot, "work");
    await mkdir(workDir, { recursive: true });
    const scene = basicFallScene({ duration: DURATION, restitution, text: "アカリ" });
    const overlay = overlayFor("phys", scene, { start: 0, duration: DURATION });
    const sheetPath = join(workDir, "sheet.html");
    await writeFile(
      sheetPath,
      renderOverlaySheet({ overlays: [overlay], edit, projectRoot, duration: DURATION }),
      "utf8",
    );

    const { browser } = await launchBrowser();
    try {
      const page = await browser.newPage();
      await page.setViewport({ width: edit.output.width, height: edit.output.height, deviceScaleFactor: 1 });
      await page.goto(pathToFileURL(sheetPath).href, { waitUntil: "networkidle0", timeout: 60000 });
      await page.evaluate(() => window.__akariReady);

      // char index 0（同一 seed・同一初期配置なので restitution 以外の条件は 2 ケースで揃う）の
      // y 軌跡を 0.02s 刻みで duration まで走査する。跳ね返りの大きさは「最初の谷（着地）の後、
      // 再び上昇するピーク」の高さで測る — restitution が高いほどこのピークが高くなるはず
      const trajectory = [];
      for (let step = 0; step <= Math.round(DURATION / 0.02); step += 1) {
        const seconds = step * 0.02;
        const states = await page.evaluate((t) => {
          const container = document.querySelector(".akari-overlay-container > .scene-content");
          window.akari.threeRuntime.render(container, t);
          return window.akari.threeRuntime.inspect(container).physics.charStates;
        }, seconds);
        trajectory.push({ seconds, y: states[0].y });
      }
      // 最初の極小点（着地・跳ね返り始点）を探す
      let firstMinimumIndex = 0;
      for (let i = 1; i < trajectory.length - 1; i += 1) {
        if (trajectory[i].y <= trajectory[i - 1].y && trajectory[i].y <= trajectory[i + 1].y) {
          firstMinimumIndex = i;
          break;
        }
      }
      const afterFirstTouch = trajectory.slice(firstMinimumIndex);
      const bouncePeakY = Math.max(...afterFirstTouch.map((s) => s.y));
      const restHeight = trajectory[trajectory.length - 1].y;
      return {
        restitution,
        firstTouchSeconds: trajectory[firstMinimumIndex].seconds,
        firstTouchY: trajectory[firstMinimumIndex].y,
        bouncePeakYAfterFirstTouch: bouncePeakY,
        bounceHeight: bouncePeakY - trajectory[firstMinimumIndex].y,
        finalRestY: restHeight,
        sampleCount: trajectory.length,
      };
    } finally {
      await browser.close();
    }
  } finally {
    await rm(projectRoot, { recursive: true, force: true });
  }
}

const low = await runCase(0.1);
const high = await runCase(0.6);

const result = {
  generated_at_note: "generated by evidence/3d-text-physics/restitution-smoke.mjs",
  scene: "basicFallScene (physics, id=phys, floor+wall*2+circle, アカリ)",
  duration_seconds: DURATION,
  floor_y: FLOOR_Y,
  low,
  high,
  bounceHeightRatio: high.bounceHeight / low.bounceHeight,
  // 高反発の方が着地後により高く跳ね返っていること（挙動が変わっていることの smoke 判定）。
  // このシーンは重力が弱く（matter-js 既定の gravity.scale 0.001）着地までが速いぶん絶対量の
  // 跳ね返り幅は小さいが、0.6 は 0.1 よりはっきり大きく跳ね返る（比で確認する）
  behaviorDiffers: high.bounceHeight > low.bounceHeight * 1.5,
};

await writeFile(
  join(ARTIFACTS_DIR, "restitution-smoke-result.json"),
  JSON.stringify(result, null, 2),
  "utf8",
);
console.log(JSON.stringify(result, null, 2));
if (!result.behaviorDiffers) process.exitCode = 1;
