// poly-decomp vendor 追加の実機検証（契約の指示 2）。実際に配布する
// vendor-3d-text-bundle.js（three-bundle.js と同じ順で読み込み）を headless Chrome へロードし、
// (1) Matter.Common.getDecomp() が poly-decomp を返す（登録済み） (2) 凹多角形の
// Bodies.fromVertices が凸包へ潰れず複数パーツへ分解される（凹みぶんだけ合計面積が
// 凸包より小さい）ことを、node の unbundled smoke（vendor 準備時に実施済み）ではなく
// 実際に出荷する bundle ファイルそのもので確認する
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { launchBrowser, makeProjectRoot, sha256File } from "./shared/fixtures.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ARTIFACTS_DIR = join(HERE, "artifacts");
const THREE_BUNDLE_PATH = resolve(HERE, "../../../overlay-runtime/src/vendor/three-bundle.js");
const TEXT_BUNDLE_PATH = resolve(HERE, "../../../overlay-runtime/src/vendor/vendor-3d-text-bundle.js");

const projectRoot = await makeProjectRoot("vendor-smoke");
try {
  const pagePath = join(projectRoot, "smoke.html");
  await writeFile(
    pagePath,
    `<!doctype html><html><head><meta charset="utf-8"></head><body>
<script src="${pathToFileURL(THREE_BUNDLE_PATH).href}"></script>
<script src="${pathToFileURL(TEXT_BUNDLE_PATH).href}"></script>
<script>
  window.__smokeResult = (function () {
    const { THREE, TroikaText, opentype, Matter } = window.AkariThree;
    const exportsPresent = {
      THREE: typeof THREE === "function" || typeof THREE === "object",
      TroikaText: typeof TroikaText === "function",
      opentype: typeof opentype === "object",
      Matter: typeof Matter === "object",
    };
    const decomp = Matter.Common.getDecomp();
    const decompRegistered = !!(decomp && typeof decomp.quickDecomp === "function");

    // U 字型の凹多角形（腕の隙間を模した簡易フィクスチャ）。面積 10（外接矩形 16 から
    // 凹みぶん 6 を引いた値）。minimumArea は既定 10 だと本テスト形状のチャンク面積 5 が
    // 切り捨てられ parts=[] になるため明示的に 0 を渡す（vendor 準備時に踏んだ実装上の注意点。
    // three-runtime.js の buildColliderBody でも同じ理由で 0 を渡している）
    const concave = [
      { x: 0, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 4 }, { x: 3, y: 4 },
      { x: 3, y: 1 }, { x: 1, y: 1 }, { x: 1, y: 4 }, { x: 0, y: 4 },
    ];
    const hullBodyBeforeRegistration = Matter.Bodies.fromVertices(2, 2, [concave], {}, true, 0.01, 0);
    const hullPartCount = hullBodyBeforeRegistration.parts.length;
    const hullArea = Matter.Vertices.area(hullBodyBeforeRegistration.vertices);

    const decomposedBody = Matter.Bodies.fromVertices(2, 2, [concave], {}, true, 0.01, 0);
    const decomposedPartCount = decomposedBody.parts.length - 1;
    const decomposedArea = decomposedBody.parts.slice(1).reduce((sum, part) => sum + part.area, 0);

    return {
      exportsPresent,
      decompRegistered,
      // 未登録時（poly-decomp 登録前と同じ挙動）: 凹多角形が凸包へ自動フォールバックする一次証拠。
      // hullPartCount は「登録後の状態」で呼んでいるため実際にはもう凸包にはならない —
      // 本当の「未登録なら凸包に潰れる」証拠は vendor 準備時の node 実測（report.md 参照）で確認済み。
      // ここでは「登録済みなら凹みが保たれる」side を bundle 実物で再確認する
      hullPartCount,
      hullArea,
      decomposedPartCount,
      decomposedArea,
      concavityPreserved: decomposedPartCount > 1 && decomposedArea < hullArea,
    };
  })();
</script>
</body></html>`,
    "utf8",
  );

  const { browser } = await launchBrowser();
  let result;
  try {
    const page = await browser.newPage();
    const pageErrors = [];
    page.on("pageerror", (e) => pageErrors.push(String(e)));
    await page.goto(pathToFileURL(pagePath).href, { waitUntil: "load", timeout: 30000 });
    result = await page.evaluate(() => window.__smokeResult);
    result.pageErrors = pageErrors;
  } finally {
    await browser.close();
  }

  const bundleBytes = (await readFile(TEXT_BUNDLE_PATH)).length;
  const bundleSha256 = await sha256File(TEXT_BUNDLE_PATH);

  const output = {
    generated_at_note: "generated by evidence/3d-text-physics/vendor-smoke.mjs",
    bundle: {
      path: "packages/overlay-runtime/src/vendor/vendor-3d-text-bundle.js",
      bytes: bundleBytes,
      sha256: bundleSha256,
    },
    result,
    pass: Boolean(
      result.exportsPresent.THREE
      && result.exportsPresent.TroikaText
      && result.exportsPresent.opentype
      && result.exportsPresent.Matter
      && result.decompRegistered
      && result.concavityPreserved
      && result.pageErrors.length === 0,
    ),
  };

  await mkdir(ARTIFACTS_DIR, { recursive: true });
  await writeFile(
    join(ARTIFACTS_DIR, "vendor-smoke-result.json"),
    JSON.stringify(output, null, 2),
    "utf8",
  );
  console.log(JSON.stringify(output, null, 2));
  if (!output.pass) process.exitCode = 1;
} finally {
  await rm(projectRoot, { recursive: true, force: true });
}
